// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltSaveScreen","status":true,"description":"セーブ／ロード画面のレイアウトを変更します。","parameters":{}},
{"name":"TPB_CastGauge","status":true,"description":"スキル発動待機時間をゲージに表示します。","parameters":{"CastGaugeColor1":"#ff0000","CastGaugeColor2":"#ffaaaa"}}
];
